# --- Data and Preprocessing Configuration ---
data:
  path: '<ABSOLUTE_PATH_TO_YOUR_QUESTIONS.CSV>'
  fasttext_path: '<ABSOLUTE_PATH_TO_VECTOR_EMBEDS.vec>'
  sample_fraction: 0.05 # Fraction of data to sample for quicker testing (0.1 = 24 hrs roughly)
  qubit_limit: 12
  test_size: 0.2  # Proportion of data to use for testing

# --- Model and QNLP Circuit Configuration ---
qnlp:
  n_layers: 1
  # Available embedding methods: 'simple_pad', 'superposition', 'entangle'
  embedding_method: 'entangle'  #Options: 'simple_pad', 'superposition', 'entangle', 'parameterized'
  rewrite_rules:
    - 'curry'
    - 'prepositional_phrase'
    - 'determiner'

# --- Training Configuration ---
training:
  epochs: 5
  base_learning_rate: 0.001
  lambda_penalty: 0.1
simulation:
  device: "lightning.gpu" # Options: "lightning.qubit", "lightning.gpu", "default.qubit"
  cpu_cores: 6